#!/bin/bash

echo "🚀 DEPLOYING FIXED FRONTEND TO NETLIFY"
echo "====================================="
echo ""
echo "✅ Fixed API URL construction issue"
echo "✅ Updated Netlify redirects order"
echo "✅ Rebuilt frontend with correct configuration"
echo ""
echo "📋 DEPLOYMENT OPTIONS:"
echo "====================="
echo ""
echo "Option 1: Manual Upload (Recommended)"
echo "1. Go to https://app.netlify.com/"
echo "2. Find your site: playful-biscuit-e5d6e1-recruiter-ai"
echo "3. Drag and drop the 'dist' folder to redeploy"
echo ""
echo "Option 2: CLI Deployment"
echo "1. Run: netlify link"
echo "2. Select your existing site when prompted"
echo "3. Run: netlify deploy --prod --dir=dist"
echo ""
echo "🌐 WHAT'S BEEN FIXED:"
echo "===================="
echo "• API URLs now correctly constructed:"
echo "  - Mass Mailing: /api/mass-mailing/campaigns (not /api/mass-mailing/api/campaigns)"
echo "  - CRM: /api/crm/pipeline-stages (not /api/crm/api/pipeline-stages)"
echo "  - Main API: /api/job-descriptions (works as before)"
echo ""
echo "• Netlify redirects properly ordered:"
echo "  1. /api/mass-mailing/* → GCP Mass Mailing Backend (port 8810)"
echo "  2. /api/crm/* → GCP CRM Backend (port 8809)"
echo "  3. /api/* → GCP Milvus Integration (port 8804)"
echo ""
echo "📁 Ready to deploy: $(pwd)/dist"
echo "🎯 This should fix all the 404 errors you were seeing!"
