cluster:
  enabled: true

kafka:
  enabled: true
  replicaCount: 1
  heapOpts: "-Xmx256M -Xms256M"
  extraEnvVars:
    - name: KAFKA_LOG_CLEANER_ENABLE
      value: "false"
    - name: KAFKA_NUM_PARTITIONS
      value: "1"
    - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
      value: "1"
    - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
      value: "1"
  startupProbe:
    enabled: true
    initialDelaySeconds: 60
    periodSeconds: 20
    timeoutSeconds: 5
    failureThreshold: 10
  persistence:
    enabled: false
  resources:
    requests:
      memory: 384Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 200m
  zookeeper:
    enabled: true
    replicaCount: 1
    extraEnvVars:
      - name: ZOO_HEAP_SIZE
        value: "128"
      - name: ZOO_MAX_CLIENT_CNXNS
        value: "60"
    persistence:
      enabled: false
    resources:
      requests:
        memory: 192Mi
        cpu: 100m
      limits:
        memory: 256Mi
        cpu: 200m

metrics:
  serviceMonitor:
    enabled: false

pulsar:
  enabled: false

pulsarv3:
  enabled: false
  bookie:
    enabled: false
  broker:
    enabled: false
  proxy:
    enabled: false
  zookeeper:
    enabled: false
  recovery:
    enabled: false

etcd:
  replicaCount: 1

minio:
  mode: standalone
  replicas: 1

msgStreamType: "kafka"

queryNode:
  replicas: 1
dataNode:
  replicas: 1
indexNode:
  replicas: 1
proxy:
  replicas: 1
rootCoord:
  replicas: 1
queryCoord:
  replicas: 1
dataCoord:
  replicas: 1
indexCoord:
  replicas: 1 