#!/bin/bash

echo "🚀 Setting up correct GCP Milvus connection"
echo "============================================="

echo "📋 Current situation:"
echo "   - Your Milvus Attu shows: 1 job description, 7 resumes"
echo "   - Backend shows: 7 job descriptions, 0 resumes"
echo "   - This means they're connecting to different Milvus instances"

echo ""
echo "🔧 To fix this, you need to:"
echo ""
echo "1. First, get your GCP cluster credentials:"
echo "   gcloud container clusters get-credentials milvus-cluster --zone us-central1-a --project taqforce"
echo ""
echo "2. Then set up port forwarding to the correct Milvus instance:"
echo "   kubectl -n milvus port-forward svc/my-milvus-attu 8000:3000"
echo ""
echo "3. The backend should connect to localhost:19530 (Milvus service port)"
echo "   (Not localhost:8000 which is the Attu web interface port)"
echo ""
echo "4. If you're using GCP Cloud Shell, make sure you're in the same shell session"
echo "   where you set up the port forwarding"
echo ""
echo "🌐 Your Milvus Attu URL:"
echo "   8000-cs-ef91557d-be10-4004-987a-cae2f5ebd130.cs-us-central1-pits.cloudshell.dev"
echo "   This shows you're using GCP Cloud Shell with port forwarding on port 8000"
echo ""
echo "📝 The backend needs to connect to the Milvus service directly, not the Attu web interface"
echo "   - Attu web interface: port 8000 (what you see in browser)"
echo "   - Milvus service: port 19530 (what backend needs to connect to)"
echo ""
echo "🔄 After setting up port forwarding, restart the backend:"
echo "   cd /Users/fayzanbhatti/Recruiter.Ai"
echo "   pkill -f 'python3 complete_backend_with_milvus.py'"
echo "   OPENAI_API_KEY='your-key' python3 complete_backend_with_milvus.py"
echo ""
echo "✅ Then test the connection:"
echo "   python3 connect_to_correct_milvus.py"
