apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-store
spec:
  provider:
    gcpsm:
      projectID: recruiter-ai-milvus
      auth:
        workloadIdentity:
          clusterLocation: us-central1-a
          clusterName: milvus-cluster
          serviceAccountRef:
            name: recruiter-ai-sa
            namespace: recruiter-ai 